#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LLVM_BIN_DIR=${DIR}/../safecode-llvm37/build/Debug+Asserts/bin

# Build LLVM bitcode files, but only if we are building an actual C file (not for, e.g. .lds linker scripts)
for var in "$@"
do
  filetype=$(file "$var" 2> /dev/null)

  if [[ (("$filetype" == *"C source"*) || ("$filetype" == *"ASCII text"*)) && ("${var##*.}" = "c") ]]
  then
    ccargs="-emit-llvm"
  fi
done

[[ "$VERBOSE" == "1" ]] && echo ${LLVM_BIN_DIR}/clang $ccargs -Oz "$@"
if ! ${LLVM_BIN_DIR}/clang $ccargs -Oz "$@"; then
  exit 1
fi

[[ "$VERBOSE" == "1" ]] && echo || true


